// Builds the static site: ./index.html ./press.html ./style.css ./presskit.json -> dist/, plus the GENERATED tokens.css (from the shared palette), the bundled fonts (copied from
// node_modules, so no request ever leaves the site) and the AI-content disclosure (generated from docs/AI_CONTENT_REGISTER.md; the build FAILS on a type it has no line for).
// Dependency-free: Node built-ins only. Run with `node --experimental-strip-types scripts/build.mjs` (the palette is TypeScript); preview with scripts/preview.mjs on :5190.
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { disclosureFrom } from "./claims.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const repo = join(root, "..", "..");

/** The text/background pairs the stylesheet uses (token names without `--`), each of which must reach WCAG AA for normal text (4.5:1). The build fails when the palette changes under them. */
export const CONTRAST_PAIRS = [
  ["ink", "paper"], ["ink", "paper-2"], ["ink", "field"], ["stamp", "paper"], ["stamp", "field"], ["brass-dark", "paper"], ["brass-dark", "field"],
  ["text", "stamp"], ["text", "stamp-dark"], ["text", "backdrop"], ["text", "scrim"], ["brass", "backdrop"], ["brass", "scrim"], ["paper", "backdrop"],
];
export const MIN_CONTRAST = 4.5;

const FONTS = [
  ["@fontsource/im-fell-english", "im-fell-english-latin-400-normal.woff2"],
  ["@fontsource/im-fell-english", "im-fell-english-latin-400-italic.woff2"],
  ["@fontsource/im-fell-english-sc", "im-fell-english-sc-latin-400-normal.woff2"],
  ["@fontsource/special-elite", "special-elite-latin-400-normal.woff2"],
];

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** tokens.css: `:root { --ink: #...; ... }` straight from the shared palette (the same variables the game publishes at start-up). */
export async function makeTokens() {
  const { paletteCssVars, contrast, PALETTE } = await import("../../../packages/shared/src/palette.ts");
  const vars = paletteCssVars();
  const ui = PALETTE.ui;
  const byName = { ink: ui.ink, paper: ui.paper, "paper-2": ui.paper2, field: ui.field, track: ui.track, brass: ui.brass, "brass-dark": ui.brassDark, stamp: ui.stamp, "stamp-dark": ui.stampDark, text: ui.text, backdrop: ui.backdrop, scrim: ui.scrim };
  const low = [];
  for (const [fg, bg] of CONTRAST_PAIRS) {
    const c = contrast(byName[fg], byName[bg]);
    if (c < MIN_CONTRAST) low.push(`${fg} on ${bg} = ${c.toFixed(2)}`);
  }
  if (low.length) throw new Error(`palette contrast below ${MIN_CONTRAST}:1 for the site's colour pairs: ${low.join("; ")}`);
  const css = `/* GENERATED by scripts/build.mjs from packages/shared/src/palette.ts (PALETTE.ui). Do not edit. */\n:root {\n${Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`).join("\n")}\n}\n`;
  return { css, vars, contrast: Object.fromEntries(CONTRAST_PAIRS.map(([a, b]) => [`${a}/${b}`, Math.round(contrast(byName[a], byName[b]) * 100) / 100])) };
}

/** The press page's AI disclosure block and the machine-readable version for presskit.json. */
export function renderDisclosure(d) {
  const items = d.lines.map((l) => `        <li><strong>${esc(l.label)}.</strong> ${esc(l.line)}</li>`).join("\n");
  const never = d.nothingModelGenerated
    ? `<p>No audio and no image in the game was generated by an AI model. The pictures and the sounds are made by code at run time.</p>`
    : `<p>Some audio or images in the game were generated by an AI model; see the list above.</p>`;
  const review = d.pending > 0
    ? `<p>Of the ${d.entries} entries in the developer's content register, ${d.pending} are marked <em>pending developer review</em>: a person has not yet read them all. That is stated here rather than hidden.</p>`
    : `<p>All ${d.entries} entries in the content register have been reviewed by the developer.</p>`;
  return `<ul class="plain">\n${items}\n      </ul>\n      ${never}\n      ${review}`;
}

export async function buildSite({ outdir = join(root, "dist"), register = join(repo, "docs", "AI_CONTENT_REGISTER.md"), registerText } = {}) {
  const disclosure = disclosureFrom(registerText ?? readFileSync(register, "utf8"));
  const tokens = await makeTokens();
  rmSync(outdir, { recursive: true, force: true });
  mkdirSync(join(outdir, "fonts"), { recursive: true });

  for (const page of ["index.html", "press.html"]) {
    let html = readFileSync(join(root, page), "utf8");
    html = html.replace("<!--@ai-disclosure-->", renderDisclosure(disclosure));
    if (html.includes("<!--@")) throw new Error(`${page}: an unreplaced build marker is left in the page`);
    writeFileSync(join(outdir, page), html);
  }
  writeFileSync(join(outdir, "tokens.css"), tokens.css);

  const require = createRequire(join(root, "package.json"));
  const need = [];
  let css = readFileSync(join(root, "style.css"), "utf8");
  for (const [pkg, file] of FONTS) {
    const dir = dirname(require.resolve(`${pkg}/package.json`));
    const src = join(dir, "files", file);
    if (!existsSync(src)) need.push(`${pkg}/files/${file}`);
    else cpSync(src, join(outdir, "fonts", file));
    const lic = join(dir, "LICENSE");
    if (existsSync(lic)) cpSync(lic, join(outdir, "fonts", `${pkg.split("/")[1]}.LICENSE.txt`));
  }
  if (need.length) throw new Error(`missing font files: ${need.join(", ")}`);
  writeFileSync(join(outdir, "style.css"), css);

  const kit = JSON.parse(readFileSync(join(root, "presskit.json"), "utf8"));
  kit.aiContent = {
    summary: disclosure.nothingModelGenerated
      ? "AI-assisted text; audio and art made by code (itself written with AI assistance). Nothing in the audio or the images was generated by a model."
      : "AI-assisted text; some audio or images were generated by a model (see lines).",
    lines: disclosure.lines.map((l) => ({ kind: l.label, text: l.line })),
    register: { entries: disclosure.entries, pendingDeveloperReview: disclosure.pending },
    nothingModelGeneratedInAudioOrImages: disclosure.nothingModelGenerated,
  };
  writeFileSync(join(outdir, "presskit.json"), `${JSON.stringify(kit, null, 2)}\n`);
  return { outdir, disclosure, tokens };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const r = await buildSite();
  console.log(`[website] built ${r.outdir} (${r.disclosure.lines.length} AI-content lines, ${r.disclosure.pending}/${r.disclosure.entries} entries pending review)`);
}
