// What the press page may CLAIM about AI-assisted content, derived from docs/AI_CONTENT_REGISTER.md (D-036, package D). The register's Type column is read; every type must be covered
// by a disclosure line below or the build FAILS, so a new kind of AI content can never ship under a page that does not mention it. A kind that is model-generated (art, images, audio or
// voices that came out of a model rather than out of code) also REMOVES the "nothing model-generated" sentence, because it would no longer be true.

/** What one kind of register entry is called on the page, and whether it is made by a model (true) or by code a model helped to write (false). */
const KINDS = {
  text: { label: "Text", model: true, line: "Written with AI assistance: interface copy, satirical lettering, dialogue and newspaper text. Everything is authored and fixed; nothing is generated while you play." },
  dialogue: { label: "Dialogue", model: true, line: "Spoken lines were written with AI assistance and are authored and fixed; nothing is generated while you play." },
  narrative: { label: "Narrative", model: true, line: "Story text was written with AI assistance and is authored and fixed." },
  localisation: { label: "Localisation", model: true, line: "Translations were produced with AI assistance." },
  sound: { label: "Audio", modelWhenNoCode: true, codeLine: "Procedurally synthesised audio: every sound and the music are computed by code at run time (code written with AI assistance). There are no audio files and no recordings.", modelLine: "Audio generated by an AI model." },
  music: { label: "Music", modelWhenNoCode: true, codeLine: "Generative music computed by code at run time (code written with AI assistance); no recordings.", modelLine: "Music generated by an AI model." },
  voice: { label: "Voice", model: true, line: "Voices generated by an AI model." },
  art: { label: "Art", modelWhenNoCode: true, codeLine: "Procedural art: characters, places and effects are drawn by code at run time (code written with AI assistance). No image was produced by an image model.", modelLine: "Images generated by an AI model." },
  image: { label: "Images", modelWhenNoCode: true, codeLine: "Images drawn by code at run time (code written with AI assistance).", modelLine: "Images generated by an AI model." },
  textures: { label: "Textures", modelWhenNoCode: true, codeLine: "Textures painted by code at run time (code written with AI assistance).", modelLine: "Textures generated by an AI model." },
  texture: { label: "Textures", modelWhenNoCode: true, codeLine: "Textures painted by code at run time (code written with AI assistance).", modelLine: "Textures generated by an AI model." },
  marketing: { label: "Marketing", model: true, line: "Marketing material produced with AI assistance." },
  "marketing images": { label: "Marketing images", model: true, line: "Marketing images produced with AI assistance." },
};

/** Kinds that are audio or pictures: a model-made one of these breaks the "nothing model-generated" sentence. */
const MEDIA = new Set(["sound", "music", "voice", "art", "image", "textures", "texture", "marketing images"]);

/** `"sound (synthesis code) + text"` -> [{ kind: "sound", qualifier: "synthesis code" }, { kind: "text", qualifier: "" }] */
export function parseTypes(cell) {
  return String(cell)
    .split("+")
    .map((p) => p.trim().toLowerCase())
    .filter(Boolean)
    .map((p) => {
      const m = /^([^()]+?)\s*(?:\(([^)]*)\))?$/.exec(p);
      return { kind: (m?.[1] ?? p).trim(), qualifier: (m?.[2] ?? "").trim() };
    });
}

/** The register's table rows (the `|` table under the heading), as { date, item, type, tool, edit, ships }. */
export function parseRegister(markdown) {
  const rows = [];
  for (const line of String(markdown).split("\n")) {
    if (!line.startsWith("|")) continue;
    const cells = line.split("|").slice(1, -1).map((c) => c.trim());
    if (cells.length < 6) continue;
    if (/^-+$/.test(cells[0].replace(/\s/g, "")) || cells[0].toLowerCase() === "date") continue;
    rows.push({ date: cells[0], item: cells[1], type: cells[2], tool: cells[3], edit: cells[4], ships: cells[5] });
  }
  return rows;
}

/**
 * Turns the register into the page's disclosure: one line per kind that appears (throws on a kind with no line), how many entries are marked pending review, and whether the
 * sentence "nothing was generated by a model in the audio or the images" is still true. Entries that do not ship are ignored.
 */
export function disclosureFrom(markdown) {
  const rows = parseRegister(markdown).filter((r) => !/^no\b/i.test(r.ships));
  const found = new Map();
  let pending = 0;
  let modelAudioOrImages = false;
  for (const r of rows) {
    if (/pending developer review|not yet auditioned/i.test(r.edit)) pending++;
    const kinds = parseTypes(r.type);
    if (kinds.length === 0) throw new Error(`AI register entry "${r.item.slice(0, 50)}..." has an empty Type: every shipped entry must say what kind of content it is (the page has no disclosure line for it)`);
    for (const { kind, qualifier } of kinds) {
      const k = KINDS[kind];
      if (!k) throw new Error(`AI register type "${kind}" (entry: ${r.item.slice(0, 50)}...) has no disclosure line: add it to scripts/claims.mjs and to the press page before shipping`);
      const code = /code|synth|procedural/.test(qualifier);
      const model = k.modelWhenNoCode ? !code : k.model === true;
      if (model && MEDIA.has(kind)) modelAudioOrImages = true;
      const line = k.modelWhenNoCode ? (code ? k.codeLine : k.modelLine) : k.line;
      const id = `${k.label}|${line}`;
      if (!found.has(id)) found.set(id, { label: k.label, line, model, entries: 0 });
      found.get(id).entries++;
    }
  }
  const lines = [...found.values()].sort((a, b) => a.label.localeCompare(b.label));
  return { lines, entries: rows.length, pending, modelAudioOrImages, nothingModelGenerated: !modelAudioOrImages };
}
